// This file is auto-generated by generate-classes.js. Do not edit it.

import { IActionable, ActionableBaseImpl } from "../gen/components/actionable.base.js";
import { LenraComponent } from '../gen/response.js';
import { Component } from './component.js';

export { IActionable };

export function Actionable<T extends LenraComponent>(child: Component<T> | T): ActionableImpl {
  return new ActionableImpl({
    _type: "actionable",
    child: Component.normalize(child),
  });
}

export class ActionableImpl extends ActionableBaseImpl {
  // Add here custom implementations
}
