// This file is auto-generated by generate-classes.js. Do not edit it.

import { IButton, ButtonBaseImpl } from "../gen/components/button.base.js";

export { IButton };

export function Button(text: IButton['text']): ButtonImpl {
  return new ButtonImpl({
    _type: "button",
    text: text,
  });
}

export class ButtonImpl extends ButtonBaseImpl {
  // Add here custom implementations
}
