// This file is auto-generated by generate-classes.js. Do not edit it.

import { IButton, ButtonBaseImpl } from "../gen/components/button.base.js";
import { LenraComponent } from '../gen/response.js';
import { Component } from './component.js';
import { IIcon } from '../gen/components/icon.base.js';

export { IButton };

export function Button(text: IButton['text']): ButtonImpl {
  return new ButtonImpl({
    _type: "button",
    text: text,
  });
}

export class ButtonImpl extends ButtonBaseImpl {
  // Add here custom implementations
  disable() {
    this.model.disabled = true;
    return this;
  }
  enable() {
    this.model.disabled = false;
    return this;
  }

  leftIcon(icon: IIcon)
  leftIcon(icon: Component<IIcon> | IIcon) {
    this.model.leftIcon = Component.normalize(icon);
    return this;
  }

  rightIcon(icon: IIcon)
  rightIcon(icon: Component<IIcon> | IIcon) {
    this.model.rightIcon = Component.normalize(icon);
    return this;
  }
}
