// This file is auto-generated by generate-classes.js. Do not edit it.

import { ICheckbox, CheckboxBaseImpl } from "../gen/components/checkbox.base.js";

export { ICheckbox };

export function Checkbox(value: ICheckbox['value']): CheckboxImpl {
  return new CheckboxImpl({
    _type: "checkbox",
    value: value,
  });
}

export class CheckboxImpl extends CheckboxBaseImpl {
  // Add here custom implementations
}
