// This file is auto-generated by generate-classes.js. Do not edit it.

import { IContainer, ContainerBaseImpl } from "../gen/components/container.base.js";

export { IContainer };

export function Container(): ContainerImpl {
  return new ContainerImpl({
    _type: "container",
    
  });
}

export class ContainerImpl extends ContainerBaseImpl {
  // Add here custom implementations
}
