// This file is auto-generated by generate-classes.js. Do not edit it.

import { IIcon } from './icon.js';
import { Component } from './component.js';
import { LenraComponent } from '../gen/response.js';
import { IDropdownButton, DropdownButtonBaseImpl } from "../gen/components/dropdownButton.base.js";

export { IDropdownButton };

export function DropdownButton<T extends LenraComponent>(text: IDropdownButton['text'], child: Component<T> | T): DropdownButtonImpl {
  return new DropdownButtonImpl({
    _type: "dropdownButton",
    text: text,
    child: Component.normalize(child),
  });
}

export class DropdownButtonImpl extends DropdownButtonBaseImpl {
  icon(icon: Component<IIcon> | IIcon) {
    return super.icon(Component.normalize(icon));
  }
}
