// This file is auto-generated by generate-classes.js. Do not edit it.

import { IDropdownButton, DropdownButtonBaseImpl } from "../gen/components/dropdownButton.base.js";

export { IDropdownButton };

export function DropdownButton(text: IDropdownButton['text'], child: IDropdownButton['child']): DropdownButtonImpl {
  return new DropdownButtonImpl({
    _type: "dropdownButton",
    text: text,
    child: child,
  });
}

export class DropdownButtonImpl extends DropdownButtonBaseImpl {
  // Add here custom implementations
}
