// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response.js';
import { Component } from './component';
import { IFlexible, FlexibleBaseImpl } from "../gen/components/flexible.base.js";

export { IFlexible };

export function Flexible<T extends LenraComponent>(child: Component<T> | T): FlexibleImpl {
  return new FlexibleImpl({
    _type: "flexible",
    child: Component.normalize(child),
  });
}

export class FlexibleImpl extends FlexibleBaseImpl {
  // Add here custom implementations
}
