// This file is auto-generated by generate-classes.js. Do not edit it.

import { IFlex, FlexBaseImpl } from "../gen/components/flex.base.js";

export { IFlex };

export function Flex(children: IFlex['children']): FlexImpl {
  return new FlexImpl({
    _type: "flex",
    children: children,
  });
}

export class FlexImpl extends FlexBaseImpl {
  // Add here custom implementations
}
