// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response';
import { Component } from './component';
import { IFlex, FlexBaseImpl } from "../gen/components/flex.base";

export { IFlex };

export function Flex(children: (Component<LenraComponent> | LenraComponent)[] = []): FlexImpl {
  return new FlexImpl({
    _type: "flex",
    children: children.map(Component.normalize),
  });
}

export class FlexImpl extends FlexBaseImpl {
  addChild(child: Component<LenraComponent> | LenraComponent) {
    this.model.children.push(Component.normalize(child));
    return this;
  }
}
