// This file is auto-generated by generate-classes.js. Do not edit it.

import { IFlexible, FlexibleBaseImpl } from "../gen/components/flexible.base.js";

export { IFlexible };

export function Flexible(child: IFlexible['child']): FlexibleImpl {
  return new FlexibleImpl({
    _type: "flexible",
    child: child,
  });
}

export class FlexibleImpl extends FlexibleBaseImpl {
  // Add here custom implementations
}
