// This file is auto-generated by generate-classes.js. Do not edit it.

import { IForm, FormBaseImpl } from "../gen/components/form.base.js";

export { IForm };

export function Form(child: IForm['child']): FormImpl {
  return new FormImpl({
    _type: "form",
    child: child,
  });
}

export class FormImpl extends FormBaseImpl {
  // Add here custom implementations
}
