// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response.js';
import { Component } from './component';
import { IForm, FormBaseImpl } from "../gen/components/form.base.js";

export { IForm };

export function Form<T extends LenraComponent>(child: Component<T> | T): FormImpl {
  return new FormImpl({
    _type: "form",
    child: Component.normalize(child),
  });
}

export class FormImpl extends FormBaseImpl {
  // Add here custom implementations
}
