// This file is auto-generated by generate-classes.js. Do not edit it.

import { IIcon, IconBaseImpl } from "../gen/components/icon.base.js";

export { IIcon };

export function Icon(value: IIcon['value']): IconImpl {
  return new IconImpl({
    _type: "icon",
    value: value,
  });
}

export class IconImpl extends IconBaseImpl {
  // Add here custom implementations
}
