// This file is auto-generated by generate-classes.js. Do not edit it.

import { Component } from './component';
import { IImage, ImageBaseImpl } from "../gen/components/image.base.js";
import { LenraComponent } from '../gen/response.js';

export { IImage };

export function Image(src: IImage['src']): ImageImpl {
  return new ImageImpl({
    _type: "image",
    src: src,
  });
}

export class ImageImpl extends ImageBaseImpl {
  errorPlaceholder<T extends LenraComponent>(errorPlaceholder: T)
  errorPlaceholder<T extends LenraComponent>(errorPlaceholder: Component<T> | T) {
    this.model.errorPlaceholder = Component.normalize(errorPlaceholder);
    return this;
  }
  framePlaceholder<T extends LenraComponent>(framePlaceholder: T)
  framePlaceholder<T extends LenraComponent>(framePlaceholder: Component<T> | T) {
    this.model.framePlaceholder = Component.normalize(framePlaceholder);
    return this;
  }
  loadingPlaceholder<T extends LenraComponent>(loadingPlaceholder: T)
  loadingPlaceholder<T extends LenraComponent>(loadingPlaceholder: Component<T> | T) {
    this.model.loadingPlaceholder = Component.normalize(loadingPlaceholder);
    return this;
  }
}
