// This file is auto-generated by generate-classes.js. Do not edit it.

import { IImage, ImageBaseImpl } from "../gen/components/image.base.js";

export { IImage };

export function Image(src: IImage['src']): ImageImpl {
  return new ImageImpl({
    _type: "image",
    src: src,
  });
}

export class ImageImpl extends ImageBaseImpl {
  // Add here custom implementations
}
