// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response.js';
import { Component } from './component';
import { IMenu, MenuBaseImpl } from "../gen/components/menu.base.js";

export { IMenu };

export function Menu(children: (Component<LenraComponent> | LenraComponent)[]): MenuImpl {
  return new MenuImpl({
    _type: "menu",
    children: children.map(Component.normalize),
  });
}

export class MenuImpl extends MenuBaseImpl {
  // Add here custom implementations
}
