// This file is auto-generated by generate-classes.js. Do not edit it.

import { IMenu, MenuBaseImpl } from "../gen/components/menu.base.js";

export { IMenu };

export function Menu(children: IMenu['children']): MenuImpl {
  return new MenuImpl({
    _type: "menu",
    children: children,
  });
}

export class MenuImpl extends MenuBaseImpl {
  // Add here custom implementations
}
