// This file is auto-generated by generate-classes.js. Do not edit it.

import { IMenuItem, MenuItemBaseImpl } from "../gen/components/menuItem.base";

export { IMenuItem };

export function MenuItem(text: IMenuItem['text']): MenuItemImpl {
  return new MenuItemImpl({
    _type: "menuItem",
    text: text,
  });
}

export class MenuItemImpl extends MenuItemBaseImpl {
  // Add here custom implementations
}
