// This file is auto-generated by generate-classes.js. Do not edit it.

import { IOverlayEntry, OverlayEntryBaseImpl } from "../gen/components/overlayEntry.base.js";

export { IOverlayEntry };

export function OverlayEntry(child: IOverlayEntry['child']): OverlayEntryImpl {
  return new OverlayEntryImpl({
    _type: "overlayEntry",
    child: child,
  });
}

export class OverlayEntryImpl extends OverlayEntryBaseImpl {
  // Add here custom implementations
}
