// This file is auto-generated by generate-classes.js. Do not edit it.

import { IRadio, RadioBaseImpl } from "../gen/components/radio.base";

export { IRadio };

export function Radio(value: IRadio['value'], groupValue: IRadio['groupValue']): RadioImpl {
  return new RadioImpl({
    _type: "radio",
    value: value,
    groupValue: groupValue,
  });
}

export class RadioImpl extends RadioBaseImpl {
  // Add here custom implementations
}
