// This file is auto-generated by generate-classes.js. Do not edit it.

import { ISlider, SliderBaseImpl } from "../gen/components/slider.base";

export { ISlider };

export function Slider(): SliderImpl {
  return new SliderImpl({
    _type: "slider",
    
  });
}

export class SliderImpl extends SliderBaseImpl {
  // Add here custom implementations
}
