// This file is auto-generated by generate-classes.js. Do not edit it.

import { IStack, StackBaseImpl } from "../gen/components/stack.base.js";

export { IStack };

export function Stack(children: IStack['children']): StackImpl {
  return new StackImpl({
    _type: "stack",
    children: children,
  });
}

export class StackImpl extends StackBaseImpl {
  // Add here custom implementations
}
