// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response';
import { Component } from './component';
import { IStack, StackBaseImpl } from "../gen/components/stack.base";

export { IStack };

export function Stack(children: (Component<LenraComponent> | LenraComponent)[] = []): StackImpl {
  return new StackImpl({
    _type: "stack",
    children: children.map(Component.normalize),
  });
}

export class StackImpl extends StackBaseImpl {
  // Add here custom implementations
}
