// This file is auto-generated by generate-classes.js. Do not edit it.

import { Component } from './component';
import { IText, TextBaseImpl } from "../gen/components/text.base";

export { IText };

export function Text(value: IText['value']): TextImpl {
  return new TextImpl({
    _type: "text",
    value: value,
  });
}

export class TextImpl extends TextBaseImpl {
  children(children: IText[])
  children(children: (Component<IText> | IText)[]) {
    return super.children(children.map(Component.normalize));
  }
}
