// This file is auto-generated by generate-classes.js. Do not edit it.

import { IText, TextBaseImpl } from "../gen/components/text.base.js";

export { IText };

export function Text(value: IText['value']): TextImpl {
  return new TextImpl({
    _type: "text",
    value: value,
  });
}

export class TextImpl extends TextBaseImpl {
  // Add here custom implementations
}
