// This file is auto-generated by generate-classes.js. Do not edit it.

import { IToggle, ToggleBaseImpl } from "../gen/components/toggle.base";

export { IToggle };

export function Toggle(value: IToggle['value']): ToggleImpl {
  return new ToggleImpl({
    _type: "toggle",
    value: value,
  });
}

export class ToggleImpl extends ToggleBaseImpl {
  // Add here custom implementations
}
