// This file is auto-generated by generate-classes.js. Do not edit it.

import { Query } from "../gen/response";
import { IView, ViewBaseImpl } from "../gen/components/view.base";
import { ViewName } from "../gen/names";

export { IView };

export function View(name: ViewName): ViewImpl {
  return new ViewImpl({
    _type: "view",
    name: name,
  });
}

export class ViewImpl extends ViewBaseImpl {
  // Add here custom implementations
  find(coll: string, query: Query, projection?: { [k: string]: unknown })
  find(find: IView['find'])
  find(param1: string | IView['find'], query?: Query, projection?: { [k: string]: unknown }) {
    if (typeof param1 === "string") { // param 1 is now guaranteed to be string
      query = query!;
      return super.find({ coll: param1, query, projection });
    }
    return super.find(param1);
  }
}
