// This file is auto-generated by generate-classes.js. Do not edit it.

import { IView, ViewBaseImpl } from "../gen/components/view.base.js";

export { IView };

export function View(name: IView['name']): ViewImpl {
  return new ViewImpl({
    _type: "view",
    name: name,
  });
}

export class ViewImpl extends ViewBaseImpl {
  // Add here custom implementations
}
