// This file is auto-generated by generate-classes.js. Do not edit it.

import { LenraComponent } from '../gen/response';
import { Component } from './component';
import { IWrap, WrapBaseImpl } from "../gen/components/wrap.base";

export { IWrap };

export function Wrap(children: (Component<LenraComponent> | LenraComponent)[] = []): WrapImpl {
  return new WrapImpl({
    _type: "wrap",
    children: children.map(Component.normalize),
  });
}

export class WrapImpl extends WrapBaseImpl {
  // Add here custom implementations
}
