// This file is auto-generated by generate-classes.js. Do not edit it.

import { IWrap, WrapBaseImpl } from "../gen/components/wrap.base.js";

export { IWrap };

export function Wrap(children: IWrap['children']): WrapImpl {
  return new WrapImpl({
    _type: "wrap",
    children: children,
  });
}

export class WrapImpl extends WrapBaseImpl {
  // Add here custom implementations
}
